# Ansible playbook to perform software updates on servers.

- name: Update system software on servers.
  hosts: "{{ hosts_group }}"
  tasks:
  
  - name: Update all Debian based systems packages to their latest version.
    become: yes
    ansible.builtin.apt:
      upgrade: "yes"  # Apparently this thing expects a string value.
      update_cache: yes 
    when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" )



  
